@startuml "MLStart"

skinparam usecase {
BackgroundColor transparent
shadowing false
}

(E: Event)
(W: Workshop) #line:red;text:red
(M: Math) #line:darkorange;text:darkorange
(A: Assignment) #line:MidnightBlue;text:MidnightBlue

(E0: 30DaysOfML Init)/ as E0 <<Taha Bouhsine>>
(E1: AI First + ML 101)/ as E1 <<Taha Bouhsine>>

(E2: Intro to Data)/ as E2 <<Taha Bouhsine>>
(E3: Intro to Colab) as E3 <<Said Elhachemy>>
(E4: Python in Kaggle) as E4 << Lahcen Oussayd >>
(E5: Supervised Machine Learning)/ as E5 <<Taha Bouhsine>>
(E5_1: Linear Regression)/ as E5_1
(E5_2: SVM)/ as E5_2
(E5_3: Decision Tree)/ as E5_3
(E5_4: Random Forest)/ as E5_4 <<Oumaima Kaissi>>
(E6: Intro to EDA)/ as E6 <<Taha Bouhsine>>
(E7: Intro to Deep Learning)/ as E7 << Ayoub Bouihrouchane >>




(W1: Supervised ML with sklearn)/ as W1 << Chaimae Majgari>> #line:red;text:red 
(W2: Intro to Python)/ as W2 #line:red;text:red
(W3: Linear Algebra with Numpy)/ as W3 <<Said Elhachemy>> #line:red;text:red
(W4: Data Preparation with Pandas)/ as W4 <<Oumaima Kaissi>> #line:red;text:red
(W5: Intro to JAX)/ as W5 <<Said Elhachemy>> #line:red;text:red
(W6: Intro to Data Visualization with Python)/ as W6 <<Souad Saidi>> #line:red;text:red
(W7: EDA with Python)/ as W7 <<Taha Bouhsine>> #line:red;text:red
(W8: Intro to TensorFlow)/ as W8 << Ayoub Bouihrouchane >> #line:red;text:red 
(W9: OOP with Python)/ as W9 #line:red;text:red
(W10: NN with JAX) as W10 <<Said Elhachemy>> #line:red;text:red
(W11: Functional Programming with Python)/ as W11 #line:red;text:red
(W12: NN with Numpy)/ as W12 #line:red;text:red

(M1: Linear algebra for ML) as M1 << El Mahjoub Abakrim >> #line:darkorange;text:darkorange
(M2: Probability for ML) as M2 << El Mahjoub Abakrim >> #line:darkorange;text:darkorange
(M3: Statistics for ML) as M3 << El Mahjoub Abakrim >> #line:darkorange;text:darkorange
(M5: Calculus for ML) as M5 << El Mahjoub Abakrim >> #line:darkorange;text:darkorange 
(M4: Information Theory for ML) as M4 << El Mahjoub Abakrim >> #line:darkorange;text:darkorange

(A1: Sklearn Classification Assignment)/ as A1 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
Heart Disease UCI Dataset
end note

(A2: Sklearn Regression Assignment)/ as A2 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
House Pricing Dataset
end note

(A3: EDA Assignment)/ as A3 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
EDA on Titanic Dataset
end note

(A4: DNN Regression with TF)/ as A4 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
Regression using DNNs with TF
end note

(A5: DNN Classification with TF)/ as A5 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
Classification using DNNs with TF
end note

(A6: NN Regression with Numpy)/ as A6 #line:MidnightBlue;text:MidnightBlue
note bottom [[http://GDSCUIZ.github.io]]
Classification using DNNs with TF
end note

M1 --> W3

M2 --> M3

M3 --> E6
M4 --> E6

M5 --> E7

E0 --> E1

E1 --> W2
E1 --> E2

E2 ---> E5
E2 --> W4
E2 ---> E6

E3 --> E7

E4 --> E7

E5 --> E7
E5 --> E6
E5 --> E5_1
E5 --> E5_2
E5 ---> E5_3
E5 ---> E5_4
E5_1 --> W1
E5_2 --> W1
E5_3 --> W1
E5_4 --> W1


E6 --> A3
E6 --> W7
E6 --> W6

E7 --> W8
E7 --> W10
E7 -- W12

W1 --> A1
W1 --> A2

W2 --> E4
W2 --> E3
W2 --> W3
W2 ---> W11

W3 ---> W4
W3 --> W5

W4 --> W6

W5 --> W10

W6 --> W7

W7 --> A3

W8 --> A4
W8 --> A5

W11 ---> W9

W12 --> A6

(Required)/
(Optional)
@enduml
